import SectionTitle from "@/components/reusable-ui/SectionTitle";
import { articles } from "@/constants/constants";
import styles from "@/styles";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import ellipse from "../../assets/ellipse.svg";

export default function Blog() {
  return (
    <>
      <Head>
        <title>Workshop By A | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main
        className={`${styles.boxWidth} ${styles.paddingX} relative pb-[100px] pt-[40px]`}
      >
        <div className="absolute sm:w-[30%] w-[55%] left-0 sm:top-[0%] ss:top-[40%] top-[40%]">
          <Image src={ellipse} alt="ellipse" />
        </div>

        <div className="flex flex-col items-center">
          <h1 className={`${styles.heading1} text-center `}>BLOG</h1>
          <div className="h-[1px] w-[60px] bg-primary mt-6 mb-12"></div>
        </div>

        <div
          className={`${styles.gap} grid sm:grid-cols-2 grid-cols-1 justify-items-center gap-10 px-4 relative`}
        >
          {articles.map((article, index) => (
            <Link
              key={index}
              href={`/blog/${article.title
                .replaceAll(" ", "-")
                .replaceAll("?", "-")}?id=${article.id}`}
              className="bg-secondary p-2 sm:w-[100%] ss:w-[70%] w-[100%]"
            >
              <article>
                <Image src={article.cover} alt="article" />

                <p className="text-gray-500 text-sm pt-2">
                  {article.date} •{" "}
                  <span className="text-tertiary font-semibold">
                    {article.author}
                  </span>
                </p>
                <h5 className={`${styles.heading5} min-h-[60px]`}>
                  {article.title}
                </h5>
                <p className={`${styles.text} description mt-3`}>
                  {article.description}
                </p>

                <button className="px-2 py-1 bg-tertiary rounded-sm text-white mt-3">
                  En voir plus
                </button>
              </article>
            </Link>
          ))}
        </div>
      </main>
    </>
  );
}
