/* eslint-disable react/no-unescaped-entities */
import PagesTitle from "@/components/reusable-ui/PagesTitle";
import styles from "@/styles";
import Head from "next/head";
import Image from "next/image";
import aboutpic from "../assets/WorkshopbyA-About.jpg";

export default function about() {
  return (
    <>
      <Head>
        <title>Workshop By A | À propos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main
        className={`${styles.boxWidth} ${styles.paddingX} relative pb-[100px] pt-[40px]`}
      >
        <PagesTitle label="À PROPOS" />

        <div className="flex">
          <div className="w-6/12">
            <p>
              Bonjour, je m'appelle Alizée et je suis une jeune entrepreneure
              passionnée par la communication digitale. Tout a commencé lorsque
              j'ai réalisé des études dans le domaine de la coiffure à l'âge de
              14 ans. Bien que j'ai aimé ce métier, j'ai rapidement compris que
              ma véritable passion résidait ailleurs.
              <br />
              <br />
              C'est ainsi que j'ai découvert le métier de community manager et
              je suis tombée amoureuse de cette profession excitante et en
              constante évolution. Mais il n'était pas facile de réaliser une
              reconversion professionnelle. J'ai dû faire preuve de beaucoup de
              persévérance, de courage et de détermination pour atteindre mon
              objectif.
              <br />
              <br />
              Après de longs mois de formation et de travail acharné, j'ai
              finalement réussi à obtenir une certification en "Création et
              développement d'une stratégie de communication digitale" en mars
              2023. C'était une grande réussite pour moi et j'ai décidé de me
              lancer dans l'entrepreneuriat.
              <br />
              <br />
              Aujourd'hui, je suis fière de pouvoir aider les entreprises à
              développer leur présence en ligne et à atteindre leur public cible
              grâce à mes compétences en marketing digital. J'ai créé ma propre
              entreprise de conseil en communication digitale et je suis
              heureuse de pouvoir aider mes clients à atteindre leurs objectifs.
              <br />
              <br />
              Pour moi, l'entrepreneuriat n'est pas seulement une question de
              travail acharné, mais aussi de passion et de détermination. Je
              suis impatiente de voir ce que l'avenir me réserve et de continuer
              à apprendre et à grandir dans cette profession passionnante.
            </p>
          </div>
          <div className="w-6/12">
            <Image src={aboutpic} alt="" className="" />
          </div>
        </div>
      </main>
    </>
  );
}
