import Head from "next/head";
import { Inter } from "@next/font/google";
import Hero from "@/components/hero/Hero";
import About from "@/components/about/About";
import Services from "@/components/services/Services";
import { useRouter } from "next/router";
import { HiArrowLongUp } from "react-icons/hi2";
import Blog from "@/components/blog/Blog";
import { client } from "@/lib/sanity.client";
import { useScroll } from "framer-motion";

const inter = Inter({ subsets: ["latin"] });
type Props = {
  posts: Post[];
};

export default function Home({ posts }: Props) {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Workshop By A</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="images/png" sizes="50x50" href="/favicon.png" />
      </Head>
      <main>
        <Hero />
        <About />
        <Services />
        <Blog posts={posts} />

        <div className="fixed right-0 bottom-10">
          <a href="#">
            <button className="xs:text-[50px] text-[35px]">
              <HiArrowLongUp />
            </button>
          </a>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "post"]';
  const posts = await client.fetch(query);
  const authorQuery = '*[_type == "author"]';
  const author = await client.fetch(authorQuery);

  return {
    props: { posts, author },
  };
};
